### ISSUE TITLE
User Feedback

### ISSUE THREAD

**Issue by thaikolja** [hassantafreshi/easy-form-builder#25]
A couple of days ago, someone sent me an email regarding Easy Form Builder. He had some questions, and I'd like to introduce them as ideas for a future version:

- [x] #26
- [x] This is a direct quote from the user: _"Is it possible to show text with links in it to other sites?  (I need to be able to get the user’s agreement to terms and conditions on providers’ sites, preferably opening in a new window)."_

Oh, and btw, what's the answer to these questions, @hassantafreshi?

**Comment by thaikolja** [comment]
Oh yeah, it connects to data remotely rather than downloading and storing them. That's not GDPR confirm. Check out here: https://github.com/hassantafreshi/easy-form-builder/blob/v3/includes/admin/class-Emsfb-panel.php

Want me to take care of it?

**Comment by hassantafreshi** [comment]
> A couple of days ago, someone sent me an email regarding Easy Form Builder. He had some questions, and I'd like to introduce them as ideas for a future version:
> 
> * [ ]  [Make sure the entire plugin is working with GDPR #26](https://github.com/hassantafreshi/easy-form-builder/issues/26)
> * [x]  This is a direct quote from the user: _"Is it possible to show text with links in it to other sites?  (I need to be able to get the user’s agreement to terms and conditions on providers’ sites, preferably opening in a new window)."_
> 
> Oh, and btw, what's the answer to these questions, @hassantafreshi?

@thaikolja 
About the link future, this field exists before, user  can find the **Link fields** on the advanced tab in the create a new form  after that drag and drop the field in the form builder section (notice that this option is just available in pro version)

about GDPR confirm. we will have an update for the validation form filled on server-side in this branch:
https://github.com/hassantafreshi/easy-form-builder/tree/dev

if it is not enough for GDPR confirm so  Please clear terms and needed for GDPR confirm in [Make sure the entire plugin is working with GDPR #26](https://github.com/hassantafreshi/easy-form-builder/issues/26) topic.

**Comment by hassantafreshi** [comment]
> Oh yeah, it connects to data remotely rather than downloading and storing them. That's not GDPR confirm. Check out here: https://github.com/hassantafreshi/easy-form-builder/blob/v3/includes/admin/class-Emsfb-panel.php
> 
> Want me to take care of it?

We validate pro version, Stripe payment or google service remotely. Could you share Which section is not GDPR confirm ?

**Comment by hassantafreshi** [comment]
This issues closed
