### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by thaikolja** [hassantafreshi/easy-form-builder#31]
I stumbled upon the file linked below and wanted to know about the status of the pro features. Have they been built yet?

https://github.com/hassantafreshi/easy-form-builder/blob/9e5d5fed79e25dab74f0e5836b86616d084608c3/includes/admin/class-Emsfb-panel.php#L111

**Comment by hassantafreshi** [comment]
Yes it built , Pro features of [Easy Form Builder](https://whitestudio.team/#price) :
- Location Picker
- Digital Signatures
- Rating Star
- Download Survey dataset CSV
- Download Form Submissions as CSV
- Advanced Forms
- Unlimited Multi step Forms
- Payment Form
- Stripe Gateway
- Heading Field
- Link Field
- Country list Field
- States/ Provinces list Field
- Offline Mode
- Advance Fields & Blocks
- Support 135+ currencies
- Remove Easy Form Builder Branding
- Save and Resume
- Drag & Drop upload file
- Response messages
- Open/Close a response(ticket)
- Download a response(ticket) as pdf file
