### ISSUE TITLE
JQuery error when submitting form

### ISSUE THREAD

**Issue by lessrand** [hassantafreshi/easy-form-builder#50]
Hello,

it seems to happen after 10min and when longer or multiple forms are opened.
We get a JQuery error saying: Error-Code JQ-500

This is a real showstopper, as we loose Visitors with non workinmg forms.

kind regards 

Randy

**Comment by hassantafreshi** [comment]
Unfortunately this limition is default of JQUERY and WordPress and we working on it.

**Comment by hassantafreshi** [comment]
Please share your form link to check your problems . @lessrand

**Comment by hassantafreshi** [comment]
We working on it
